import Slider from "../Components/Slider/Slider";
import Head from "next/head";

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Slider />
      </>
   );
}
